name: Contribute Extension to Raycast

on:
  workflow_dispatch:
  push:
    branches:
      - main # or your primary dev branch

env:
  BRANCH_NAME: tdrayson-password-link
  EXTENSION_FOLDER: password-link
  FORK_REPO: tdrayson/extensions
  BASE_REPO: raycast/extensions

jobs:
  contribute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this extension repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Clone your fork of raycast/extensions
        env:
          TOKEN: ${{ secrets.RAYCAST_TOKEN }}
        run: |
          git clone https://$TOKEN@github.com/${{ env.FORK_REPO }} raycast-extensions
          cd raycast-extensions
          git remote add upstream https://github.com/${{ env.BASE_REPO }}.git
          git fetch upstream
          git checkout -b ${{ env.BRANCH_NAME }} upstream/main

      - name: Copy this extension into the correct folder
        run: |
          rm -rf raycast-extensions/extensions/${{ env.EXTENSION_FOLDER }}
          mkdir -p raycast-extensions/extensions/${{ env.EXTENSION_FOLDER }}
          cp -r . raycast-extensions/extensions/${{ env.EXTENSION_FOLDER }}
          rm -rf raycast-extensions/extensions/${{ env.EXTENSION_FOLDER }}/.git*
          cd raycast-extensions
          git add extensions/${{ env.EXTENSION_FOLDER }}
          git commit -m "Add ${{ env.EXTENSION_FOLDER }} extension" || echo "No changes"
          git push https://x-access-token:${{ secrets.RAYCAST_TOKEN }}@github.com/${{ env.FORK_REPO }}.git ${{ env.BRANCH_NAME }}

      - name: Create pull request into raycast/extensions
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.RAYCAST_TOKEN }}
          title: "Add `${{ env.EXTENSION_FOLDER }}` extension"
          body: |
            This PR adds the `${{ env.EXTENSION_FOLDER }}` extension from `tdrayson/raycast-password-link`.

            ✅ Added to: `extensions/${{ env.EXTENSION_FOLDER }}`
          base: main
          head: ${{ env.BRANCH_NAME }}
          repository: ${{ env.BASE_REPO }}
